# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Cralix\Desktop\qtCashier\app_modules\receiptModule\ui/receiptItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(290, 221)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.productsWidget = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productsWidget.sizePolicy().hasHeightForWidth())
        self.productsWidget.setSizePolicy(sizePolicy)
        self.productsWidget.setObjectName("productsWidget")
        self.gridLayout.addWidget(self.productsWidget, 6, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 4, 1, 1)
        self.commentForm = QtWidgets.QFormLayout()
        self.commentForm.setObjectName("commentForm")
        self.commentLabel = QtWidgets.QLabel(Form)
        self.commentLabel.setObjectName("commentLabel")
        self.commentForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.commentLabel)
        self.commentEdit = QtWidgets.QPlainTextEdit(Form)
        self.commentEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.commentEdit.setReadOnly(True)
        self.commentEdit.setObjectName("commentEdit")
        self.commentForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.commentEdit)
        self.gridLayout.addLayout(self.commentForm, 7, 3, 1, 1)
        self.timeForm = QtWidgets.QFormLayout()
        self.timeForm.setObjectName("timeForm")
        self.timeLabel = QtWidgets.QLabel(Form)
        self.timeLabel.setObjectName("timeLabel")
        self.timeForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.timeLabel)
        self.timeEdit = QtWidgets.QLabel(Form)
        self.timeEdit.setObjectName("timeEdit")
        self.timeForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.timeEdit)
        self.gridLayout.addLayout(self.timeForm, 2, 3, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 10, 3, 1, 1)
        self.idForm = QtWidgets.QFormLayout()
        self.idForm.setObjectName("idForm")
        self.idLabel = QtWidgets.QLabel(Form)
        self.idLabel.setObjectName("idLabel")
        self.idForm.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.idLabel)
        self.idEdit = QtWidgets.QLabel(Form)
        self.idEdit.setObjectName("idEdit")
        self.idForm.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.idEdit)
        self.gridLayout.addLayout(self.idForm, 8, 3, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.commentLabel.setText(_translate("Form", "Комментарий к чеку:"))
        self.timeLabel.setText(_translate("Form", "Чек от"))
        self.timeEdit.setText(_translate("Form", "02.11.2021 21:12:"))
        self.idLabel.setText(_translate("Form", "ID:"))
        self.idEdit.setText(_translate("Form", "0"))
